version: "3"

services:
  app:
    image: docker-userdataapp-dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./models:/app/models
      - ./public:/app/public
      - ./styles:/app/styles
      - ./utils:/app/utils
    env_file:
      - ./.env
